// Generated by CoffeeScript 1.12.4
(function() {
  var icon, request, url;

  request = require('request');

  url = require('url');

  icon = require('./icon');

  module.exports = {
    get: function(_url, fn) {
      _url = url.parse(_url);
      _url = _url.protocol + '//' + _url.host;
      return request(_url, function(err, res, body) {
        var list;
        if (err) {
          return fn({
            "apple-touch-icon": [],
            "shortcut icon": [],
            "icon": []
          });
        } else {
          list = icon.get(_url, body);
          return fn(list);
        }
      });
    }
  };

}).call(this);
