// Generated by CoffeeScript 1.12.4
(function() {
  var Icon;

  Icon = (function() {
    function Icon() {
      this.url = require('url');
      this.path = require('path');
      this.reg = {
        "apple-touch-icon": /<link rel=\"apple-touch-icon\".*?>/g,
        "shortcut icon": /<link rel=\"shortcut icon\".*?>/g,
        "fluid-icon": /<link rel=\"fluid-icon\".*?>/g,
        "icon": /<link rel=\"icon\".*?>/g
      };
    }

    Icon.prototype.get = function(url, body) {
      var _reg, key, list, ref;
      list = {};
      ref = this.reg;
      for (key in ref) {
        _reg = ref[key];
        list[key] = this.checkIcon(_reg, url, body);
      }
      return list;
    };

    Icon.prototype.checkIcon = function(reg, url, body) {
      var _link, href, i, len, link, list;
      list = [];
      link = null;
      url = this.url.parse(url);
      link = body.match(reg);
      if (!link) {
        link = [];
      }
      for (i = 0, len = link.length; i < len; i++) {
        _link = link[i];
        href = _link.match(/href=\".*?\"/);
        if (href) {
          href = href[0].replace(/(href=|\")/g, '');
          if (!href.match(/(http:|https:)/)) {
            href = this.path.join(url.host, href);
            href = url.protocol + '//' + href;
          }
          list.push(href);
        }
      }
      return list;
    };

    return Icon;

  })();

  module.exports = new Icon();

}).call(this);
